/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BondListing {
  'diversification' : Diversification,
  'status' : BondStatus,
  'couponRate' : number,
  'couponType' : CouponType,
  'riskTags' : Array<RiskTag>,
  'minInvestment' : bigint,
  'issuer' : string,
  'ratingAgency' : string,
  'launchDate' : Time,
  'rating' : number,
  'redemptionType' : RedemptionType,
  'tenure' : bigint,
  'faceValue' : bigint,
  'repaymentFrequency' : RepaymentFrequency,
}
export type BondStatus = { 'active' : null } |
  { 'fullyRedeemed' : null } |
  { 'matured' : Time } |
  { 'defaulted' : null };
export type CouponType = { 'zeroCoupon' : null } |
  { 'coupon' : bigint };
export type Diversification = { 'investmentAmount' : bigint } |
  { 'riskLevel' : string };
export interface Investment {
  'repayments' : Array<Repayment>,
  'investedOn' : Time,
  'bondId' : number,
  'isActive' : boolean,
  'investmentPlan' : Diversification,
  'amount' : bigint,
}
export interface PortfolioSummary {
  'totalInvested' : bigint,
  'activeHoldings' : Array<Investment>,
  'investmentDistribution' : Diversification,
}
export type RedemptionType = { 'bulletRepayment' : null } |
  { 'staggeredRedemption' : null } |
  { 'prepayment' : null };
export interface Repayment {
  'status' : RepaymentStatus,
  'dueDate' : Time,
  'principalComponent' : bigint,
  'amount' : bigint,
  'interestAmount' : bigint,
}
export type RepaymentFrequency = { 'annually' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null };
export type RepaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null } |
  { 'defaulted' : null };
export type RiskTag = { 'unsecured' : null } |
  { 'secured' : null } |
  { 'seniorSecured' : null } |
  { 'securedByMovableAssets' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'kycStatus' : { 'verified' : null } |
    { 'pending' : null } |
    { 'rejected' : null },
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBondListing' : ActorMethod<[number], [] | [BondListing]>,
  'getBondListings' : ActorMethod<[], Array<BondListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserPortfolio' : ActorMethod<[], PortfolioSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeDefaultBonds' : ActorMethod<[], undefined>,
  'invest' : ActorMethod<[number, bigint, Diversification], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];