/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Diversification = IDL.Variant({
  'investmentAmount' : IDL.Nat,
  'riskLevel' : IDL.Text,
});
export const Time = IDL.Int;
export const BondStatus = IDL.Variant({
  'active' : IDL.Null,
  'fullyRedeemed' : IDL.Null,
  'matured' : Time,
  'defaulted' : IDL.Null,
});
export const CouponType = IDL.Variant({
  'zeroCoupon' : IDL.Null,
  'coupon' : IDL.Nat,
});
export const RiskTag = IDL.Variant({
  'unsecured' : IDL.Null,
  'secured' : IDL.Null,
  'seniorSecured' : IDL.Null,
  'securedByMovableAssets' : IDL.Null,
});
export const RedemptionType = IDL.Variant({
  'bulletRepayment' : IDL.Null,
  'staggeredRedemption' : IDL.Null,
  'prepayment' : IDL.Null,
});
export const RepaymentFrequency = IDL.Variant({
  'annually' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
});
export const BondListing = IDL.Record({
  'diversification' : Diversification,
  'status' : BondStatus,
  'couponRate' : IDL.Nat16,
  'couponType' : CouponType,
  'riskTags' : IDL.Vec(RiskTag),
  'minInvestment' : IDL.Nat,
  'issuer' : IDL.Text,
  'ratingAgency' : IDL.Text,
  'launchDate' : Time,
  'rating' : IDL.Nat32,
  'redemptionType' : RedemptionType,
  'tenure' : IDL.Nat,
  'faceValue' : IDL.Nat,
  'repaymentFrequency' : RepaymentFrequency,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'kycStatus' : IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'phoneNumber' : IDL.Text,
});
export const RepaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
  'defaulted' : IDL.Null,
});
export const Repayment = IDL.Record({
  'status' : RepaymentStatus,
  'dueDate' : Time,
  'principalComponent' : IDL.Nat,
  'amount' : IDL.Nat,
  'interestAmount' : IDL.Nat,
});
export const Investment = IDL.Record({
  'repayments' : IDL.Vec(Repayment),
  'investedOn' : Time,
  'bondId' : IDL.Nat32,
  'isActive' : IDL.Bool,
  'investmentPlan' : Diversification,
  'amount' : IDL.Nat,
});
export const PortfolioSummary = IDL.Record({
  'totalInvested' : IDL.Nat,
  'activeHoldings' : IDL.Vec(Investment),
  'investmentDistribution' : Diversification,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBondListing' : IDL.Func([IDL.Nat32], [IDL.Opt(BondListing)], ['query']),
  'getBondListings' : IDL.Func([], [IDL.Vec(BondListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserPortfolio' : IDL.Func([], [PortfolioSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeDefaultBonds' : IDL.Func([], [], []),
  'invest' : IDL.Func([IDL.Nat32, IDL.Nat, Diversification], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Diversification = IDL.Variant({
    'investmentAmount' : IDL.Nat,
    'riskLevel' : IDL.Text,
  });
  const Time = IDL.Int;
  const BondStatus = IDL.Variant({
    'active' : IDL.Null,
    'fullyRedeemed' : IDL.Null,
    'matured' : Time,
    'defaulted' : IDL.Null,
  });
  const CouponType = IDL.Variant({
    'zeroCoupon' : IDL.Null,
    'coupon' : IDL.Nat,
  });
  const RiskTag = IDL.Variant({
    'unsecured' : IDL.Null,
    'secured' : IDL.Null,
    'seniorSecured' : IDL.Null,
    'securedByMovableAssets' : IDL.Null,
  });
  const RedemptionType = IDL.Variant({
    'bulletRepayment' : IDL.Null,
    'staggeredRedemption' : IDL.Null,
    'prepayment' : IDL.Null,
  });
  const RepaymentFrequency = IDL.Variant({
    'annually' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const BondListing = IDL.Record({
    'diversification' : Diversification,
    'status' : BondStatus,
    'couponRate' : IDL.Nat16,
    'couponType' : CouponType,
    'riskTags' : IDL.Vec(RiskTag),
    'minInvestment' : IDL.Nat,
    'issuer' : IDL.Text,
    'ratingAgency' : IDL.Text,
    'launchDate' : Time,
    'rating' : IDL.Nat32,
    'redemptionType' : RedemptionType,
    'tenure' : IDL.Nat,
    'faceValue' : IDL.Nat,
    'repaymentFrequency' : RepaymentFrequency,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'kycStatus' : IDL.Variant({
      'verified' : IDL.Null,
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'phoneNumber' : IDL.Text,
  });
  const RepaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
    'defaulted' : IDL.Null,
  });
  const Repayment = IDL.Record({
    'status' : RepaymentStatus,
    'dueDate' : Time,
    'principalComponent' : IDL.Nat,
    'amount' : IDL.Nat,
    'interestAmount' : IDL.Nat,
  });
  const Investment = IDL.Record({
    'repayments' : IDL.Vec(Repayment),
    'investedOn' : Time,
    'bondId' : IDL.Nat32,
    'isActive' : IDL.Bool,
    'investmentPlan' : Diversification,
    'amount' : IDL.Nat,
  });
  const PortfolioSummary = IDL.Record({
    'totalInvested' : IDL.Nat,
    'activeHoldings' : IDL.Vec(Investment),
    'investmentDistribution' : Diversification,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBondListing' : IDL.Func([IDL.Nat32], [IDL.Opt(BondListing)], ['query']),
    'getBondListings' : IDL.Func([], [IDL.Vec(BondListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserPortfolio' : IDL.Func([], [PortfolioSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeDefaultBonds' : IDL.Func([], [], []),
    'invest' : IDL.Func([IDL.Nat32, IDL.Nat, Diversification], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };