/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PortfolioSummary {
    totalInvested: bigint;
    activeHoldings: Array<Investment>;
    investmentDistribution: Diversification;
}
export interface Investment {
    repayments: Array<Repayment>;
    investedOn: Time;
    bondId: number;
    isActive: boolean;
    investmentPlan: Diversification;
    amount: bigint;
}
export type CouponType = {
    __kind__: "zeroCoupon";
    zeroCoupon: null;
} | {
    __kind__: "coupon";
    coupon: bigint;
};
export interface BondListing {
    diversification: Diversification;
    status: BondStatus;
    couponRate: number;
    couponType: CouponType;
    riskTags: Array<RiskTag>;
    minInvestment: bigint;
    issuer: string;
    ratingAgency: string;
    launchDate: Time;
    rating: number;
    redemptionType: RedemptionType;
    tenure: bigint;
    faceValue: bigint;
    repaymentFrequency: RepaymentFrequency;
}
export type BondStatus = {
    __kind__: "active";
    active: null;
} | {
    __kind__: "fullyRedeemed";
    fullyRedeemed: null;
} | {
    __kind__: "matured";
    matured: Time;
} | {
    __kind__: "defaulted";
    defaulted: null;
};
export type Diversification = {
    __kind__: "investmentAmount";
    investmentAmount: bigint;
} | {
    __kind__: "riskLevel";
    riskLevel: string;
};
export interface Repayment {
    status: RepaymentStatus;
    dueDate: Time;
    principalComponent: bigint;
    amount: bigint;
    interestAmount: bigint;
}
export interface BondListingWithId {
    listing: BondListing;
    bondId: number;
}
export interface UserProfile {
    name: string;
    email: string;
    kycStatus: Variant_verified_pending_rejected;
    phoneNumber: string;
}
export enum RedemptionType {
    bulletRepayment = "bulletRepayment",
    staggeredRedemption = "staggeredRedemption",
    prepayment = "prepayment"
}
export enum RepaymentFrequency {
    annually = "annually",
    quarterly = "quarterly",
    monthly = "monthly"
}
export enum RepaymentStatus {
    pending = "pending",
    paid = "paid",
    overdue = "overdue",
    defaulted = "defaulted"
}
export enum RiskTag {
    unsecured = "unsecured",
    secured = "secured",
    seniorSecured = "seniorSecured",
    securedByMovableAssets = "securedByMovableAssets"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_verified_pending_rejected {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBondListing(bondId: number, listing: BondListing): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpdateCouponRates(): Promise<bigint>;
    getAdminUserPortfolio(user: Principal): Promise<PortfolioSummary>;
    getBondListing(bondId: number): Promise<BondListing | null>;
    getBondListings(): Promise<Array<BondListing>>;
    getBondListingsWithIds(): Promise<Array<BondListingWithId>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserPortfolio(): Promise<PortfolioSummary>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    invest(bondId: number, amount: bigint, diversification: Diversification): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeBondListing(bondId: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBondListing(bondId: number, listing: BondListing): Promise<void>;
    updateBondListingDates(): Promise<void>;
}
import type { BondListing as _BondListing, BondListingWithId as _BondListingWithId, BondStatus as _BondStatus, CouponType as _CouponType, Diversification as _Diversification, Investment as _Investment, PortfolioSummary as _PortfolioSummary, RedemptionType as _RedemptionType, Repayment as _Repayment, RepaymentFrequency as _RepaymentFrequency, RepaymentStatus as _RepaymentStatus, RiskTag as _RiskTag, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBondListing(arg0: number, arg1: BondListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBondListing(arg0, to_candid_BondListing_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBondListing(arg0, to_candid_BondListing_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpdateCouponRates(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateCouponRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateCouponRates();
            return result;
        }
    }
    async getAdminUserPortfolio(arg0: Principal): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUserPortfolio(arg0);
                return from_candid_PortfolioSummary_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUserPortfolio(arg0);
            return from_candid_PortfolioSummary_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBondListing(arg0: number): Promise<BondListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBondListing(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBondListing(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBondListings(): Promise<Array<BondListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBondListings();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBondListings();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBondListingsWithIds(): Promise<Array<BondListingWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBondListingsWithIds();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBondListingsWithIds();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPortfolio(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPortfolio();
                return from_candid_PortfolioSummary_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPortfolio();
            return from_candid_PortfolioSummary_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async invest(arg0: number, arg1: bigint, arg2: Diversification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.invest(arg0, arg1, to_candid_Diversification_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.invest(arg0, arg1, to_candid_Diversification_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeBondListing(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBondListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBondListing(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBondListing(arg0: number, arg1: BondListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBondListing(arg0, to_candid_BondListing_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBondListing(arg0, to_candid_BondListing_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBondListingDates(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBondListingDates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBondListingDates();
            return result;
        }
    }
}
function from_candid_BondListingWithId_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BondListingWithId): BondListingWithId {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_BondListing_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BondListing): BondListing {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_BondStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BondStatus): BondStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_CouponType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CouponType): CouponType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Diversification_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Diversification): Diversification {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Investment_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Investment): Investment {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioSummary_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioSummary): PortfolioSummary {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RedemptionType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedemptionType): RedemptionType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_RepaymentFrequency_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepaymentFrequency): RepaymentFrequency {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_RepaymentStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepaymentStatus): RepaymentStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Repayment_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Repayment): Repayment {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_RiskTag_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskTag): RiskTag {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BondListing]): BondListing | null {
    return value.length === 0 ? null : from_candid_BondListing_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalInvested: bigint;
    activeHoldings: Array<_Investment>;
    investmentDistribution: _Diversification;
}): {
    totalInvested: bigint;
    activeHoldings: Array<Investment>;
    investmentDistribution: Diversification;
} {
    return {
        totalInvested: value.totalInvested,
        activeHoldings: from_candid_vec_n20(_uploadFile, _downloadFile, value.activeHoldings),
        investmentDistribution: from_candid_Diversification_n28(_uploadFile, _downloadFile, value.investmentDistribution)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repayments: Array<_Repayment>;
    investedOn: _Time;
    bondId: number;
    isActive: boolean;
    investmentPlan: _Diversification;
    amount: bigint;
}): {
    repayments: Array<Repayment>;
    investedOn: Time;
    bondId: number;
    isActive: boolean;
    investmentPlan: Diversification;
    amount: bigint;
} {
    return {
        repayments: from_candid_vec_n23(_uploadFile, _downloadFile, value.repayments),
        investedOn: value.investedOn,
        bondId: value.bondId,
        isActive: value.isActive,
        investmentPlan: from_candid_Diversification_n28(_uploadFile, _downloadFile, value.investmentPlan),
        amount: value.amount
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RepaymentStatus;
    dueDate: _Time;
    principalComponent: bigint;
    amount: bigint;
    interestAmount: bigint;
}): {
    status: RepaymentStatus;
    dueDate: Time;
    principalComponent: bigint;
    amount: bigint;
    interestAmount: bigint;
} {
    return {
        status: from_candid_RepaymentStatus_n26(_uploadFile, _downloadFile, value.status),
        dueDate: value.dueDate,
        principalComponent: value.principalComponent,
        amount: value.amount,
        interestAmount: value.interestAmount
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diversification: _Diversification;
    status: _BondStatus;
    couponRate: number;
    couponType: _CouponType;
    riskTags: Array<_RiskTag>;
    minInvestment: bigint;
    issuer: string;
    ratingAgency: string;
    launchDate: _Time;
    rating: number;
    redemptionType: _RedemptionType;
    tenure: bigint;
    faceValue: bigint;
    repaymentFrequency: _RepaymentFrequency;
}): {
    diversification: Diversification;
    status: BondStatus;
    couponRate: number;
    couponType: CouponType;
    riskTags: Array<RiskTag>;
    minInvestment: bigint;
    issuer: string;
    ratingAgency: string;
    launchDate: Time;
    rating: number;
    redemptionType: RedemptionType;
    tenure: bigint;
    faceValue: bigint;
    repaymentFrequency: RepaymentFrequency;
} {
    return {
        diversification: from_candid_Diversification_n28(_uploadFile, _downloadFile, value.diversification),
        status: from_candid_BondStatus_n33(_uploadFile, _downloadFile, value.status),
        couponRate: value.couponRate,
        couponType: from_candid_CouponType_n35(_uploadFile, _downloadFile, value.couponType),
        riskTags: from_candid_vec_n37(_uploadFile, _downloadFile, value.riskTags),
        minInvestment: value.minInvestment,
        issuer: value.issuer,
        ratingAgency: value.ratingAgency,
        launchDate: value.launchDate,
        rating: value.rating,
        redemptionType: from_candid_RedemptionType_n40(_uploadFile, _downloadFile, value.redemptionType),
        tenure: value.tenure,
        faceValue: value.faceValue,
        repaymentFrequency: from_candid_RepaymentFrequency_n42(_uploadFile, _downloadFile, value.repaymentFrequency)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listing: _BondListing;
    bondId: number;
}): {
    listing: BondListing;
    bondId: number;
} {
    return {
        listing: from_candid_BondListing_n31(_uploadFile, _downloadFile, value.listing),
        bondId: value.bondId
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    kycStatus: {
        verified: null;
    } | {
        pending: null;
    } | {
        rejected: null;
    };
    phoneNumber: string;
}): {
    name: string;
    email: string;
    kycStatus: Variant_verified_pending_rejected;
    phoneNumber: string;
} {
    return {
        name: value.name,
        email: value.email,
        kycStatus: from_candid_variant_n51(_uploadFile, _downloadFile, value.kycStatus),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
} | {
    defaulted: null;
}): RepaymentStatus {
    return "pending" in value ? RepaymentStatus.pending : "paid" in value ? RepaymentStatus.paid : "overdue" in value ? RepaymentStatus.overdue : "defaulted" in value ? RepaymentStatus.defaulted : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    investmentAmount: bigint;
} | {
    riskLevel: string;
}): {
    __kind__: "investmentAmount";
    investmentAmount: bigint;
} | {
    __kind__: "riskLevel";
    riskLevel: string;
} {
    return "investmentAmount" in value ? {
        __kind__: "investmentAmount",
        investmentAmount: value.investmentAmount
    } : "riskLevel" in value ? {
        __kind__: "riskLevel",
        riskLevel: value.riskLevel
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    fullyRedeemed: null;
} | {
    matured: _Time;
} | {
    defaulted: null;
}): {
    __kind__: "active";
    active: null;
} | {
    __kind__: "fullyRedeemed";
    fullyRedeemed: null;
} | {
    __kind__: "matured";
    matured: Time;
} | {
    __kind__: "defaulted";
    defaulted: null;
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "fullyRedeemed" in value ? {
        __kind__: "fullyRedeemed",
        fullyRedeemed: value.fullyRedeemed
    } : "matured" in value ? {
        __kind__: "matured",
        matured: value.matured
    } : "defaulted" in value ? {
        __kind__: "defaulted",
        defaulted: value.defaulted
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zeroCoupon: null;
} | {
    coupon: bigint;
}): {
    __kind__: "zeroCoupon";
    zeroCoupon: null;
} | {
    __kind__: "coupon";
    coupon: bigint;
} {
    return "zeroCoupon" in value ? {
        __kind__: "zeroCoupon",
        zeroCoupon: value.zeroCoupon
    } : "coupon" in value ? {
        __kind__: "coupon",
        coupon: value.coupon
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unsecured: null;
} | {
    secured: null;
} | {
    seniorSecured: null;
} | {
    securedByMovableAssets: null;
}): RiskTag {
    return "unsecured" in value ? RiskTag.unsecured : "secured" in value ? RiskTag.secured : "seniorSecured" in value ? RiskTag.seniorSecured : "securedByMovableAssets" in value ? RiskTag.securedByMovableAssets : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bulletRepayment: null;
} | {
    staggeredRedemption: null;
} | {
    prepayment: null;
}): RedemptionType {
    return "bulletRepayment" in value ? RedemptionType.bulletRepayment : "staggeredRedemption" in value ? RedemptionType.staggeredRedemption : "prepayment" in value ? RedemptionType.prepayment : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annually: null;
} | {
    quarterly: null;
} | {
    monthly: null;
}): RepaymentFrequency {
    return "annually" in value ? RepaymentFrequency.annually : "quarterly" in value ? RepaymentFrequency.quarterly : "monthly" in value ? RepaymentFrequency.monthly : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): Variant_verified_pending_rejected {
    return "verified" in value ? Variant_verified_pending_rejected.verified : "pending" in value ? Variant_verified_pending_rejected.pending : "rejected" in value ? Variant_verified_pending_rejected.rejected : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Investment>): Array<Investment> {
    return value.map((x)=>from_candid_Investment_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Repayment>): Array<Repayment> {
    return value.map((x)=>from_candid_Repayment_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RiskTag>): Array<RiskTag> {
    return value.map((x)=>from_candid_RiskTag_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BondListing>): Array<BondListing> {
    return value.map((x)=>from_candid_BondListing_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BondListingWithId>): Array<BondListingWithId> {
    return value.map((x)=>from_candid_BondListingWithId_n46(_uploadFile, _downloadFile, x));
}
function to_candid_BondListing_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BondListing): _BondListing {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BondStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BondStatus): _BondStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CouponType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponType): _CouponType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Diversification_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Diversification): _Diversification {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RedemptionType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RedemptionType): _RedemptionType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_RepaymentFrequency_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepaymentFrequency): _RepaymentFrequency {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_RiskTag_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskTag): _RiskTag {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diversification: Diversification;
    status: BondStatus;
    couponRate: number;
    couponType: CouponType;
    riskTags: Array<RiskTag>;
    minInvestment: bigint;
    issuer: string;
    ratingAgency: string;
    launchDate: Time;
    rating: number;
    redemptionType: RedemptionType;
    tenure: bigint;
    faceValue: bigint;
    repaymentFrequency: RepaymentFrequency;
}): {
    diversification: _Diversification;
    status: _BondStatus;
    couponRate: number;
    couponType: _CouponType;
    riskTags: Array<_RiskTag>;
    minInvestment: bigint;
    issuer: string;
    ratingAgency: string;
    launchDate: _Time;
    rating: number;
    redemptionType: _RedemptionType;
    tenure: bigint;
    faceValue: bigint;
    repaymentFrequency: _RepaymentFrequency;
} {
    return {
        diversification: to_candid_Diversification_n3(_uploadFile, _downloadFile, value.diversification),
        status: to_candid_BondStatus_n5(_uploadFile, _downloadFile, value.status),
        couponRate: value.couponRate,
        couponType: to_candid_CouponType_n7(_uploadFile, _downloadFile, value.couponType),
        riskTags: to_candid_vec_n9(_uploadFile, _downloadFile, value.riskTags),
        minInvestment: value.minInvestment,
        issuer: value.issuer,
        ratingAgency: value.ratingAgency,
        launchDate: value.launchDate,
        rating: value.rating,
        redemptionType: to_candid_RedemptionType_n12(_uploadFile, _downloadFile, value.redemptionType),
        tenure: value.tenure,
        faceValue: value.faceValue,
        repaymentFrequency: to_candid_RepaymentFrequency_n14(_uploadFile, _downloadFile, value.repaymentFrequency)
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    kycStatus: Variant_verified_pending_rejected;
    phoneNumber: string;
}): {
    name: string;
    email: string;
    kycStatus: {
        verified: null;
    } | {
        pending: null;
    } | {
        rejected: null;
    };
    phoneNumber: string;
} {
    return {
        name: value.name,
        email: value.email,
        kycStatus: to_candid_variant_n56(_uploadFile, _downloadFile, value.kycStatus),
        phoneNumber: value.phoneNumber
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskTag): {
    unsecured: null;
} | {
    secured: null;
} | {
    seniorSecured: null;
} | {
    securedByMovableAssets: null;
} {
    return value == RiskTag.unsecured ? {
        unsecured: null
    } : value == RiskTag.secured ? {
        secured: null
    } : value == RiskTag.seniorSecured ? {
        seniorSecured: null
    } : value == RiskTag.securedByMovableAssets ? {
        securedByMovableAssets: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RedemptionType): {
    bulletRepayment: null;
} | {
    staggeredRedemption: null;
} | {
    prepayment: null;
} {
    return value == RedemptionType.bulletRepayment ? {
        bulletRepayment: null
    } : value == RedemptionType.staggeredRedemption ? {
        staggeredRedemption: null
    } : value == RedemptionType.prepayment ? {
        prepayment: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepaymentFrequency): {
    annually: null;
} | {
    quarterly: null;
} | {
    monthly: null;
} {
    return value == RepaymentFrequency.annually ? {
        annually: null
    } : value == RepaymentFrequency.quarterly ? {
        quarterly: null
    } : value == RepaymentFrequency.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "investmentAmount";
    investmentAmount: bigint;
} | {
    __kind__: "riskLevel";
    riskLevel: string;
}): {
    investmentAmount: bigint;
} | {
    riskLevel: string;
} {
    return value.__kind__ === "investmentAmount" ? {
        investmentAmount: value.investmentAmount
    } : value.__kind__ === "riskLevel" ? {
        riskLevel: value.riskLevel
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_verified_pending_rejected): {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
} {
    return value == Variant_verified_pending_rejected.verified ? {
        verified: null
    } : value == Variant_verified_pending_rejected.pending ? {
        pending: null
    } : value == Variant_verified_pending_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "active";
    active: null;
} | {
    __kind__: "fullyRedeemed";
    fullyRedeemed: null;
} | {
    __kind__: "matured";
    matured: Time;
} | {
    __kind__: "defaulted";
    defaulted: null;
}): {
    active: null;
} | {
    fullyRedeemed: null;
} | {
    matured: _Time;
} | {
    defaulted: null;
} {
    return value.__kind__ === "active" ? {
        active: value.active
    } : value.__kind__ === "fullyRedeemed" ? {
        fullyRedeemed: value.fullyRedeemed
    } : value.__kind__ === "matured" ? {
        matured: value.matured
    } : value.__kind__ === "defaulted" ? {
        defaulted: value.defaulted
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "zeroCoupon";
    zeroCoupon: null;
} | {
    __kind__: "coupon";
    coupon: bigint;
}): {
    zeroCoupon: null;
} | {
    coupon: bigint;
} {
    return value.__kind__ === "zeroCoupon" ? {
        zeroCoupon: value.zeroCoupon
    } : value.__kind__ === "coupon" ? {
        coupon: value.coupon
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RiskTag>): Array<_RiskTag> {
    return value.map((x)=>to_candid_RiskTag_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
